### ISSUE TITLE
UD/UM ordering mismatch

### ISSUE THREAD

**Issue by DavidLKing** [unimorph/ud-compatibility#1]
Hi all, 

I was noticing that `marry.py` orders the UD features in the order they appear as opposed to ordering them how they are in Unimorph. Is there any way to remedy this? 

For example, the following line from UD (as output by `marry.py`):
`17	ist	sein	AUX	VAFIN	FIN;V;IND;3;SG;PRS	27	cop	_	_`
should have the following order:
`V;IND;PRS;3;SG` 
and where `FIN` is optional. 

I'm putting these into a system which is sensitive to order, so random ordering is breaking my application. 

Thanks in advance!
--David

**Comment by aryamccarthy** [comment]
Hi David, due to life circumstances, I'm away from school and not able to make this change anytime soon.

I'm also not convinced that it *ought* to be made. UniMorph makes no promises about the order of the dimensions; each bundle is a *set* of globally unique features. 

If you really need it sorted, you can do that in your application. Make sure to also sort within the higher-level features: conjunction ("·+·"), disjunction ("·/·"), and negation ("non{·}"). Once you do this, string equality will work. A (semantically) better way would be to use a UniMorph object in your code and treat these strings as serializations of that object.

**Comment by DavidLKing** [comment]
I definitely understand life circumstances, no need to worry about that.

I am still concerned though. Even if we make the assumption that standardizing order isn't necessary, isn't the `FIN` in my original example supposed to be removed given the `GermanTranslator` code snippet below:
```python3
class GermanTranslator(Translator):
    def lgspec_assert(self, cols, tags):
        assert "V" in tags or "N" in tags or "V.PTCP" in tags or "V.CVB" in tags or "V.MSDR" in tags
        # assert tags != {"N"}
        # assert tags != {"V"}

    def lgspec_modify(self, cols, um):
        tags = set(um.split(";"))
        for gender in {"MASC", "FEM", "NEUT", "{MASC/NEUT}"}:
            if gender in tags:
                tags.remove(gender)
        tags.discard("FIN")
        if tags == {"V", "V.PTCP"}:
            tags = {"PST", "V.PTCP"}
        return ";".join(tags)
```
I'm willing to solve the issue in a variety of ways, but if there's a deeper bug, I (or someone) should probably address that first

**Comment by aryamccarthy** [comment]
Yeah, it should definitely be removed. Are you making sure to use the `--langs de` option, so it uses the `GermanTranslator` instead of the generic `Translator`?

**Comment by DavidLKing** [comment]
I am. I've used the following two commands:
```bash
python marry.py convert --ud data/raw/UD/UD_German-master/de_gsd-ud-train.conllu --lang de
python marry.py convert --ud data/raw/UD/UD_German-master/de_gsd-ud-train.conllu -l de
```
My understanding is they should be analogous. Both keep the `FIN` feature (not to mention they put it in different places every time the program is called).
